version: 1

disable_existing_loggers: true

root:
  level: INFO
  handlers:
    - stream_handler

loggers:
  server:
    level: DEBUG
    handlers:
      - stream_handler
    propagate: no

handlers:
  stream_handler:
    class: logging.StreamHandler
    formatter: stream_formatter
    stream: ext://sys.stdout

formatters:
  stream_formatter:
    format: "%(asctime)s PID- %(process)d %(levelname)s %(pathname)s %(funcName)s %(lineno)d %(message)s"
