"""Adds job_id as pk in sentimetn model

Revision ID: 002
Revises: 001
Create Date: 2020-08-30 09:46:17.739016

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment', sa.Column('job_id', sa.String(length=50), nullable=False))
    op.drop_column('sentiment', 'id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sentiment', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.drop_column('sentiment', 'job_id')
    # ### end Alembic commands ###
